name: mecel
description: A new Flutter project.
publish_to: 'none'

version: 0.4.11+24

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  url_launcher: ^6.0.18
  shared_preferences: ^2.0.13
  package_info_plus: ^1.3.0
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/languages/
    - assets/flags/
