name: wordle
description: A new Flutter project.
publish_to: 'none'

version: 0.2.1+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  package_info_plus: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/
