name: Build & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Only works with v2
      - run: |
          mkdir -p build/web
          echo "mecel.raxys.app" > build/web/CNAME.txt
      - uses: subosito/flutter-action@v1
      - uses: erickzanardo/flutter-gh-pages@v6
